### ISSUE TITLE
I cannot contact the author 

### ISSUE THREAD

**Issue by cosmointeractive** [diyphpdeveloper/cms-canvas#11]
Hi I was working on a project using CMS Canvas and so went to the website for the documentation. It seems that you have allowed your domain to expire. cmscanvas.com is down! Are you offloading this project?

**Comment by davidrahusen** [comment]
Hi, for me the page is still working. Maybe it was just a temporary issue.

**Comment by cosmointeractive** [comment]
It looked like his domain had expired at the time. He has renewed it, site is live now.

**Comment by mannym** [comment]
hi friends, It seems that the CM-Canvas has no continuity, besides the framework that is based (codeigniter) soon change 3.0 almost completely Objects oriented. I Do not want to keep depreciated functions and unable to solve problems. I've been watching processwire and I think a much more interesting project to do the daily work, with many modules and a good user forum.I hope they serve my answer. CMS-canvas is out for me.  Sorry 4 my bad english, and best regards.  


     El Viernes 5 de junio de 2015 15:07, Cosmo <notifications@github.com> escribió:
   

 It looked like his domain had expired at the time. He has renewed it, site is live now. —

**Comment by mannym** [comment]
real "live site". 
https://processwire.com/talk/

**Comment by diyphpdeveloper** [comment]
Hi guys, Yes I accidentally let the domain expire. My bad. It is back up now. I currently have no plans to write any new functionality for the CodeIgniter version of CMSCavas as I believe CodeIgniter is a dying framework.

I am currently working on a version of CMSCanvas that is built on the Laravel framework (https://github.com/diyphpdeveloper/cms-canvas-laravel). This project is still heavily under development and do not yet know when it will be ready for production use.
