### ISSUE TITLE
Isuse on http://www.cmscanvas.com/ site.

### ISSUE THREAD

**Issue by kosta90s** [diyphpdeveloper/cms-canvas#14]
Problem with sessions on http://www.cmscanvas.com/ .
http://i.imgur.com/nmKs6no.png

**Comment by dansanti** [comment]
I remember that this is a problem with your server provider, because not support the time zone that you are configuring. Also is a common CI 2 bug, i don't know if still in CI 3

**Comment by diyphpdeveloper** [comment]
This has been fixed.
