### ISSUE TITLE
how to use https

### ISSUE THREAD

**Issue by elpoleto** [diyphpdeveloper/cms-canvas#16]
Hi, is there any way to make cms canvas use https? i tried to config htaccess but i gaet a loop redirect. it seems that the program force http only

**Comment by elpoleto** [comment]
even if i force site_url in config i get a redirect loop

**Comment by KeiroD** [comment]
Have you tried the following .htaccess rules:

```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^www\.domain\.com$ [NC]
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

This should work for you as it'd allow you to force SSL. I'll be testing this soon, myself.
