### ISSUE TITLE
Can not start the cms after successfull installation!

### ISSUE THREAD

**Issue by Wmas** [diyphpdeveloper/cms-canvas#17]
I have the same issue posted by  'keilcarbon'.
This question is never been answered so I am wondering if it will be answered now.
Firefox say:
"
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
"

Any help will be appreciated.

I would like to upgrade the all project to CI3

Thanks for your help.

**Comment by cosmointeractive** [comment]
After grabbing a fresh copy of the 1.1 version I installed it and got a redirect issue (no errors); I could not view any pages apart from the front (home) page. Here is what I did to fix it. Opened .htaccess file and altered line 6 from `RewriteBase /` to `RewriteBase /playground/cms-canvas_v1.1/` as cmscanvas was installed in two directories from the root. After that i would access all pages front/admin without any issues.

**Comment by Wmas** [comment]
Thanks for sharing this.

I have tried all the possible combinations around the RewriteBase but I get still the same behavior. By the way you was lucy you could see the homepage , I can not see the home page either.

**Comment by Wmas** [comment]
Thanks for your reply.

I will try to re-install the all application once more and I let you know.

Cheers

Franco
franco@webline-studio.nl

**Comment by cosmointeractive** [comment]
Make sure all required modules are enabled i.e. mod_rewrite. Try installing WordPress to ensure its not an issue with MAMP etc.

**Comment by Wmas** [comment]
WordPress?
Sorry but I don't get you now. Is this CMS made to be used with WordPress? Because I dont use it.

Cheers

**Comment by cosmointeractive** [comment]
No it's not meant to be used with WordPress. cmscanvas is a CMS itself, WordPress is another. I was merely suggesting that you installed WordPress in order to see whether or not it would install successfully. I was hoping to helping you narrow down your issue to MAMP or cmscanvas. 

Nonetheless, it seems that you figured out your issue since you closed this issue... Mind sharing with me your resolution?

**Comment by Wmas** [comment]
Thanks for your reply.

I have tried everything possible but unfortunately the problem persists.

I think I must go for something else. It’s a pity the developer don’t support this anymore. In this case I think he should
mention it. This to avoid people loosing time for nothing.

Cheers

Franco Magliozzi
franco@webline-studio.nl
