### ISSUE TITLE
TwigBridge\Extension\CmsCanvas\Theme does not exist

### ISSUE THREAD

**Issue by burimaliu** [diyphpdeveloper/cms-canvas#18]
I am getting `TwigBridge\Extension\CmsCanvas\Theme does not exist` when i try to use content/entry route.

**Comment by diyphpdeveloper** [comment]
This sounds like your using an unstable version of the code. The issue was fixed in commit https://github.com/diyphpdeveloper/cms-canvas/commit/16cc3e1a5add78b394f7a33501f0e9e3c6a52100 which is in the v2.1 release.
