### ISSUE TITLE
Render as Template - Only seems to work on entries that have a route associated with them

### ISSUE THREAD

**Issue by timitek** [diyphpdeveloper/cms-canvas#20]
If I check this box, it only seems to render the content as a template, if I have also specified a route on the page tab.  If I just create a blog entry and browse to it, the content is not parsed as a template.  What should I do?

**Comment by diyphpdeveloper** [comment]
I committed a fix for this in 3df45749fe1d16c8423fb3a2187b8e2bc6ef7fb1 and tagged it as v2.1.4. You should be able to do a composer update and it should work now.
