### ISSUE TITLE
Unable to search by Entry Id Bug - src/CmsCanvas/Content/Entry/Builder.php:393

### ISSUE THREAD

**Issue by timitek** [diyphpdeveloper/cms-canvas#21]
src/CmsCanvas/Content/Entry/Builder.php:393
should be 
if ($entryIds === null || $entryIds === '') {
instead of 
if ($entryIds === null || $entryIds !== '') {

**Comment by timitek** [comment]
P.S. - I tried to create a new branch and then create a P.R. - But didn't have permission to create the new branch.  What is the proper way for others to contribute code changes?  Fork the project first?

**Comment by diyphpdeveloper** [comment]
Good find. Fixed it in commit 4bdf885ed1327fe31da06d6a638ef41da157cd77 and tagged it as v2.1.5. 

As for contributing, yes, fork the project and push changes to your repository. Once the code is ready create a pull request for it.

Regards
